//
//  plot.test.ts
//  md.vscode — the ```plot fence, against the oracle the site itself produced.
//
//  WHERE THE EXPECTATIONS COME FROM
//  --------------------------------
//  `fixtures/plot-vectors.json` was generated by running nettrash.me's own
//  Rust — `render_plot_svg`, `nice_step`, `format_label` and
//  `preprocess_math_expr`, extracted verbatim from
//  `frontend/src/components/math.rs` — over 403 inputs: 81 tick spacings, 100
//  tick labels (each with the four Rust primitives that produced it), 162
//  evaluations, 38 malformed expressions and 22 whole figures. Every number in
//  it is recorded twice, once as JSON and once as the IEEE-754 bit pattern, so
//  "close enough" cannot creep in.
//
//  It is an oracle, not a specification. Six of the behaviours it records are
//  bugs, and this suite asserts the **fixed** behaviour for those, in a table
//  that names each one and what the site did. Everything else must match the
//  vector exactly — there is no third category, and no row is skipped: a row
//  either matches its vector or appears in one of the correction tables below.
//
//  The other three ports (md, md.macOS, md.Android) are written against this
//  file's twin, from the same JSON, which is what makes "the same plot" a
//  claim rather than a hope.
//

import { describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import {
  evaluate,
  formatExponential,
  formatFixed,
  formatLabel,
  niceStep,
  parseExpression,
  parsePlot,
  plotCacheStats,
  PlotError,
  plotSVG,
  pow10,
  renderPlot,
  resetPlotCache,
} from '../src/render/plot';
import { renderBody, renderDocument } from '../src/render/html';
import { contentOPF, xhtml } from '../src/export/epub';
import { diagrams, menuTitle, standaloneDocument, typeName } from '../src/export/svg';
import { DIAGRAM_SELECTOR } from '../src/export/renderHost';
import { latexDocument } from '../src/export/latex';

const FIXTURES = path.join(__dirname, 'fixtures');
const GOLDEN = path.join(FIXTURES, 'golden');

interface Vectors {
  niceStep: { input: number; output: number; outputBits: string }[];
  formatLabel: {
    input: number | string;
    inputBits: string;
    output: string;
    rustPrimitives: { fmt_1e: string; fmt_2f: string; as_i64: string; round: string };
  }[];
  eval: { expr: string; x: number | string; result: number | string; resultBits: string }[];
  parseErrors: { expr: string; stage: string; error: string | null }[];
  svg: {
    name: string;
    expr: string;
    xMin: number;
    xMax: number;
    yMin: number;
    yMax: number;
    firstPoint: string | null;
    lastPoint: string | null;
    polylineCount: number;
    lineCount: number;
    textCount: number;
    xStep: number;
    yStep: number;
    xTickLabels: string[];
    yTickLabels: string[];
  }[];
}

/**
 * Read at test time from a copy inside the suite, so the corpus travels with
 * the repository and a run needs nothing outside it.
 */
const VECTORS: Vectors = JSON.parse(
  fs.readFileSync(path.join(FIXTURES, 'plot-vectors.json'), 'utf8'),
) as Vectors;

/** `nan`, `inf` and `-inf` are JSON strings — JSON has no literal for them. */
function real(value: number | string): number {
  if (value === 'nan') return Number.NaN;
  if (value === 'inf') return Number.POSITIVE_INFINITY;
  if (value === '-inf') return Number.NEGATIVE_INFINITY;
  return value as number;
}

/** The big-endian IEEE-754 bit pattern, the way the vectors record a double. */
function bits(value: number): string {
  const buffer = Buffer.alloc(8);
  buffer.writeDoubleBE(value, 0);
  return buffer.toString('hex');
}

// MARK: - §1 nice_step — ported verbatim, so every row must match

describe('niceStep', () => {
  it('reproduces all 81 recorded spacings, bit for bit', () => {
    expect(VECTORS.niceStep).toHaveLength(81);
    for (const row of VECTORS.niceStep) {
      expect(bits(niceStep(real(row.input))), `niceStep(${row.input})`).toBe(row.outputBits);
    }
  });

  it('takes each of the four branches', () => {
    // norm <= 1.5, <= 3, <= 7, else — the `10 * mag` branch is the one a
    // careless port drops, and it is what draws [-32, 32] with a step of 10.
    expect(niceStep(8)).toBe(1);
    expect(niceStep(20)).toBe(2);
    expect(niceStep(50)).toBe(5);
    expect(niceStep(64)).toBe(10);
  });

  // MARK: - The decade, and why it is not a `pow`
  //
  // THIS WAS A REAL FAILURE, NOT A HYPOTHETICAL. The pushed v1.2.0 (fd71a4e)
  // computed the decade as `Math.pow(10, Math.floor(Math.log10(rough)))` and
  // went red on GitHub Actions (Node 20) with three failures in this file,
  // while all 437 tests passed on the development machine (Node 26):
  //
  //     niceStep > reproduces all 81 recorded spacings, bit for bit
  //     the two corrected axis behaviours > keeps the tick that lands exactly
  //         on the maximum        (nine x labels expected, eight drawn)
  //     the 22 recorded figures > tiny_range: x
  //
  // THE AXIS IS THE ENGINE VERSION, NOT THE CPU — the earlier wording here
  // blamed "Linux x64 vs macOS arm64" and sent the next reader to the wrong
  // place. Comparing `Math.pow(10, n)` with the literal `1e<n>` for all 632
  // integer exponents in [-323, 308]:
  //
  //     Node 20, arm64   68 of 632      Node 20, x86-64   69 of 632
  //     Node 22, arm64   68 of 632      Node 24, arm64     2 (e = 23, 210)
  //     Node 26, arm64    0 of 632      Darwin libm pow    0 — all 632 right
  //     OpenJDK 21       Math.pow(10.0, -5.0) is one ULP below its literal
  //
  // Node 20 is wrong on both architectures and Node 26 is right on both. CI
  // pins Node 20 because that is what VS Code 1.95's extension host runs; this
  // machine runs Node 26, the one version with a perfect score, which is why
  // review missed it, and Darwin's libm is correct for every exponent, so md
  // and md.macOS cannot see it at all. On the decade this renderer needs:
  //
  //     rough = 9.999999999999999e-5              bits 3f1a36e2eb1c432c
  //     Node 26:  Math.pow(10, -4) === 1e-4       bits 3f1a36e2eb1c432d
  //     Node 20:  Math.pow(10, -4)                bits 3f1a36e2eb1c432c
  //
  // It was diagnosed by stubbing Math.pow to the value the older engine
  // returns: with the pushed v1.2.0 arithmetic those exact three fail and
  // nothing else does. That stub is not what either test below does — read
  // their comments for what each one actually guarantees.
  //
  // `pow` is not correctly rounded and is not specified to be, in any of the
  // five languages this renderer is written in. One ULP of `mag` moves `norm`
  // across a threshold of the 1/2/5/10 ladder, which changes the step, which
  // changes how many ticks the axis has and what they say — drawn output, not
  // just a number in a test. `log10` is not correctly rounded either, so its
  // `floor` cannot be trusted at a decade boundary and is treated here as a
  // guess to be corrected.
  //
  // The fix is to read the decade off a correctly-rounded decimal literal and
  // pin the exponent by exact comparison. `Math.pow(10, e)` must never come
  // back — in this file or in md, md.macOS or md.Android, which transliterate
  // it. The second test below is the family's one real mechanism guard: it
  // makes `Math.pow` throw, so a reintroduced `pow` fails on every engine and
  // every platform, and md / md.macOS / md.Android point at it because a
  // correct libm leaves them no way to reproduce the failure themselves.

  it('builds every decade from a decimal literal, bit for bit', () => {
    // The CONTRACT, not the mechanism: `pow10(e)` must equal the literal
    // `1e<e>` to the bit. Decimal→double conversion is correctly rounded by
    // specification in JS, Swift, Kotlin and Rust; `pow` is not.
    //
    // Be clear about what this cannot do. On an engine whose `pow` already
    // agrees with the literal at these exponents — Node 26 here, and Darwin's
    // libm under the md and md.macOS twins of this test — every assertion
    // below passes whether `pow10` parses a literal or calls `Math.pow`, so
    // running it green proves the value, never the mechanism. It does bite on
    // an affected engine: e = -4 is one of Node 20's 68 disagreements, and
    // Node 20 is what CI runs. The check that holds on every engine is the
    // next test, which replaces `Math.pow` with a function that throws.
    expect(bits(pow10(-4))).toBe(bits(1e-4));
    expect(bits(pow10(-4))).toBe('3f1a36e2eb1c432d');
    const literals: readonly (readonly [number, number])[] = [
      [-9, 1e-9], [-7, 1e-7], [-5, 1e-5], [-4, 1e-4], [-3, 1e-3], [-2, 1e-2],
      [-1, 1e-1], [0, 1e0], [1, 1e1], [2, 1e2], [3, 1e3], [6, 1e6], [9, 1e9],
      [12, 1e12], [15, 1e15],
    ];
    for (const [exponent, literal] of literals) {
      expect(bits(pow10(exponent)), `pow10(${exponent})`).toBe(bits(literal));
    }
    // A decade below the normal range still parses correctly — the vectors
    // carry one, at rough = 2.781342323134e-309.
    expect(bits(pow10(-309))).toBe(bits(1e-309));
    // The limits `floor(log10 rough)` reaches on the degenerate ranges the
    // vectors record, which is what keeps niceStep(0) === 0 and
    // niceStep(inf) === inf. `Number('1e-Infinity')` would be NaN.
    expect(pow10(Number.NEGATIVE_INFINITY)).toBe(0);
    expect(pow10(Number.POSITIVE_INFINITY)).toBe(Number.POSITIVE_INFINITY);
    expect(pow10(Number.NaN)).toBeNaN();
  });

  it('gets the boundary decade right without Math.pow, and survives a wrong log10', () => {
    // The family's mechanism guard — the one check in the four ports that a
    // correct `pow` cannot hide: `Math.pow` is replaced by a function that
    // throws, so any reintroduction of `pow` in the decade path fails here
    // regardless of engine version or platform, and `log10` is then perturbed
    // by ±1 decade with all 81 oracle rows still required to match.
    //
    // `tiny_range`: [0.0001, 0.0009] is the figure the CI failure was drawn
    // from. Its rough is one ULP below the decade, so the emitted step must be
    // the literal 1e-4 — on every engine, whatever `Math.pow` says there.
    const range = 0.0009 - 0.0001;
    expect(bits(range / 8)).toBe('3f1a36e2eb1c432c');
    expect(bits(niceStep(range))).toBe(bits(1e-4));

    const pow = Math.pow;
    const log10 = Math.log10;
    try {
      // If the decade ever goes back to a `pow`, this throws instead of
      // silently returning an engine-dependent double.
      Math.pow = (() => {
        throw new Error('niceStep must not call Math.pow — see the note above');
      }) as typeof Math.pow;
      // And `floor(log10)` is only a guess: hand it the two answers a
      // differently-rounded `log10` could give — ±1 decade — and demand all 81
      // oracle rows still match. Both are corrected by the exact comparison
      // against pow10.
      for (const [name, wrong] of [
        ['one decade low', (x: number) => log10(x) - 1],
        ['one decade high', (x: number) => log10(x) + 1],
      ] as const) {
        Math.log10 = wrong as typeof Math.log10;
        expect(bits(niceStep(range)), `tiny_range, ${name}`).toBe(bits(1e-4));
        for (const row of VECTORS.niceStep) {
          expect(bits(niceStep(real(row.input))), `niceStep(${row.input}), ${name}`).toBe(
            row.outputBits,
          );
        }
      }
    } finally {
      Math.pow = pow;
      Math.log10 = log10;
    }
  });
});

// MARK: - §2 format_label — ported with two corrections

/**
 * The nine labels the site prints wrong, and what this renderer prints instead.
 *
 * All nine are the same defect: `format_label`'s integer branch prints
 * `val as i64`, which **truncates**, so a tick that arrives one ULP below a
 * whole number loses a whole unit. SPEC §1.4 replaces the truncation with a
 * round, which is what `round()` in the same condition already implied.
 */
const CORRECTED_LABELS: readonly { input: number; site: string; ours: string }[] = [
  { input: 0.9999999999, site: '0', ours: '1' },
  { input: -0.9999999999, site: '0', ours: '-1' },
  { input: 2.9999999996, site: '2', ours: '3' },
  { input: -2.9999999996, site: '-2', ours: '-3' },
  { input: 999.9999999999, site: '999', ours: '1000' },
  { input: -999.9999999999, site: '-999', ours: '-1000' },
  { input: 123.99999999995, site: '123', ours: '124' },
  { input: -123.99999999995, site: '-123', ours: '-124' },
  { input: 999.9999999999999, site: '999', ours: '1000' },
];

function correctedLabel(input: number | string): { site: string; ours: string } | null {
  if (typeof input !== 'number') return null;
  for (const row of CORRECTED_LABELS) if (row.input === input) return row;
  return null;
}

describe('formatLabel', () => {
  it('reproduces all 100 recorded labels, but for the nine the site truncates', () => {
    expect(VECTORS.formatLabel).toHaveLength(100);
    let corrected = 0;
    for (const row of VECTORS.formatLabel) {
      const fix = correctedLabel(row.input);
      const got = formatLabel(real(row.input));
      if (fix === null) {
        expect(got, `formatLabel(${row.input})`).toBe(row.output);
      } else {
        expect(row.output, `the vector still records the site's ${row.input}`).toBe(fix.site);
        expect(got, `formatLabel(${row.input})`).toBe(fix.ours);
        corrected++;
      }
    }
    // Every row of the correction table was reached — a table entry that no
    // vector exercises is a claim about nothing.
    expect(corrected).toBe(CORRECTED_LABELS.length);
  });

  it('writes Rust’s exponential, not the platform’s', () => {
    // THE cross-platform hazard, pinned on all 100 values: `1.0e3` and not
    // `1.0e+3` (JavaScript), `1.0e+03` (C, Java) or `1.0E3`; and ties to even
    // on the exact binary value, not the half-up rounding `toExponential` and
    // `String.format` both perform.
    for (const row of VECTORS.formatLabel) {
      expect(formatExponential(real(row.input), 1), `{:.1e} of ${row.input}`).toBe(
        row.rustPrimitives.fmt_1e,
      );
    }
    expect((1250).toExponential(1)).toBe('1.3e+3'); // what the platform would have said
    expect(formatExponential(1250, 1)).toBe('1.2e3'); // 1.25 → ties to even
    expect(formatExponential(1350, 1)).toBe('1.4e3'); // 1.35 → ties to even, upward
    expect(formatExponential(0.0125, 1)).toBe('1.3e-2'); // not a tie: the double is above it
    expect(formatExponential(5e-324, 1)).toBe('4.9e-324'); // the smallest subnormal
  });

  it('writes Rust’s fixed form, not toFixed', () => {
    for (const row of VECTORS.formatLabel) {
      // Past 25 significant digits `{:.2}` prints the double's whole exact
      // expansion (1e300 is 301 digits of it). `format_label` sends everything
      // from 1000 up to the exponential branch, so the fixed formatter is never
      // asked for one, and it stops at the digits it can decide a rounding on.
      if (row.rustPrimitives.fmt_2f.length > 30) continue;
      expect(formatFixed(real(row.input), 2), `{:.2} of ${row.input}`).toBe(
        row.rustPrimitives.fmt_2f,
      );
    }
    expect((0.125).toFixed(2)).toBe('0.13'); // what the platform would have said
    expect(formatFixed(0.125, 2)).toBe('0.12'); // an exact tie, rounded to even
    expect(formatFixed(8.125, 2)).toBe('8.12');
    expect(formatFixed(2.675, 2)).toBe('2.67'); // the double is below the tie
    expect(formatFixed(999.999, 2)).toBe('1000.00'); // the carry runs off the fraction
    expect(formatFixed(-0, 2)).toBe('-0.00'); // Rust keeps the sign
  });
});

// MARK: - §3 The expression language

/**
 * The evaluations where this renderer deliberately answers differently.
 *
 * Four of the five families are SPEC §1.3's corrections; the fifth is the
 * `math::` prefix, which is not a language feature at all but the site's own
 * preprocessor showing through — it rewrites every roster name to `math::…`
 * before handing the text to evalexpr, so `math::sin(x)` happens to work
 * there. It is not in the roster, so it is a parse error here.
 */
const CORRECTED_EVAL: readonly { expr: string; x?: number; value: number; why: string }[] = [
  // 1. floor / ceil / round draw. The site registers them bare and then asks
  //    evalexpr for `math::floor`, which is unbound, so all 1001 samples fail
  //    and `broken_floor_no_curve.svg` has no polyline at all.
  { expr: 'floor(x)', x: 2.7, value: 2, why: 'floor works' },
  { expr: 'floor(x)', x: -2.5, value: -3, why: 'floor works' },
  { expr: 'ceil(x)', x: 2.1, value: 3, why: 'ceil works' },
  { expr: 'ceil(x)', x: -2.5, value: -2, why: 'ceil works' },
  { expr: 'round(x)', x: 2.5, value: 3, why: 'round works, ties away from zero' },
  { expr: 'round(x)', x: -2.5, value: -3, why: 'round works, ties away from zero' },
  { expr: 'round(x)', x: 0.5, value: 1, why: 'round works, ties away from zero' },
  // 2. Comparisons and the Boolean operators are numbers, so they compose.
  { expr: 'x==1', x: 1, value: 1, why: 'comparisons yield 1.0 / 0.0' },
  { expr: 'x!=1', x: 1, value: 0, why: 'comparisons yield 1.0 / 0.0' },
  { expr: 'x<1', x: 0, value: 1, why: 'comparisons yield 1.0 / 0.0' },
  { expr: 'x<=1', x: 1, value: 1, why: 'comparisons yield 1.0 / 0.0' },
  { expr: 'x>1', x: 2, value: 1, why: 'comparisons yield 1.0 / 0.0' },
  { expr: 'x>=1', x: 1, value: 1, why: 'comparisons yield 1.0 / 0.0' },
  { expr: '(x>0)*2', x: 1, value: 2, why: 'a comparison multiplies' },
  { expr: '!x', x: 1, value: 0, why: 'negation is numeric' },
  { expr: '1&&1', value: 1, why: 'a number is a truth value' },
  { expr: '1<2<3', value: 1, why: 'comparisons chain left-associatively' },
  // 3. `^` is right-associative.
  { expr: '2^3^2', value: 512, why: '2^(3^2), not (2^3)^2' },
  // 4. Everything is a double.
  { expr: '5/2', value: 2.5, why: 'no integer division' },
  { expr: '-7/2', value: -3.5, why: 'no integer division' },
  { expr: '7/2', value: 3.5, why: 'no integer division' },
  { expr: '2+3*4-5/2', value: 11.5, why: 'no integer division' },
  { expr: '1/0', value: Number.POSITIVE_INFINITY, why: 'division by zero is ±∞, not an error' },
  { expr: '0/0', value: Number.NaN, why: '0/0 is NaN, not an error' },
  { expr: '1%0', value: Number.NaN, why: 'x%0 is NaN, not an error' },
];

/**
 * Expressions this language does not have.
 *
 * Every one of them is a **parse error** here, which is the point: on the site
 * most of these parse and then die silently at evaluation time, which is why a
 * typo currently looks like an empty chart rather than a message.
 */
const NOT_IN_THE_LANGUAGE: readonly string[] = [
  // Not in the roster. evalexpr carries them; the four ports share a roster.
  'min(x,0)', 'max(x,0)', 'if(x>0,1,-1)', 'log(8,2)', 'typeof(x)',
  // The site's preprocessor showing through.
  'math::floor(x)', 'math::sin(x)', 'math::math::sin(x)', 'math::log(8,2)',
  // Unknown names, and names that are nearly right.
  'mysin(x)', 'x_sin(x)', 'SIN(x)', 'sinx', 'foo(x)', 'y', 'X',
  'true&&false', 'true||false', '!true',
  // Wrong arity — an error, not a silently empty chart.
  'sqrt(1,2)', 'hypot(3)', 'atan2(1)', 'sin()',
  // Types and syntax the language has no use for.
  '"abc"', '(1,2)', 'x=1', '0x10',
];

/**
 * Rows where V8's libm and Rust's libm disagree in the last bit.
 *
 * Three of 162, all inverse trigonometry at 0.5, all within one ULP. Nothing
 * can be done about it — `asin` is not correctly rounded in any of the four
 * runtimes — and nothing needs to be: one ULP is 10⁻¹⁶ of a pixel coordinate.
 * They are named rather than tolerated wholesale, so a *real* divergence in
 * any other function still fails.
 */
const LIBM_ULP: readonly { expr: string; x: number }[] = [
  { expr: 'atanh(x)', x: 0.5 },
  { expr: 'asin(x)', x: 0.5 },
  { expr: 'acos(x)', x: 0.5 },
];

function corrected(expr: string, x: number): { value: number; why: string } | null {
  for (const row of CORRECTED_EVAL) {
    if (row.expr !== expr) continue;
    if (row.x !== undefined && row.x !== x) continue;
    return { value: row.value, why: row.why };
  }
  return null;
}

function isLibmRow(expr: string, x: number): boolean {
  for (const row of LIBM_ULP) if (row.expr === expr && row.x === x) return true;
  return false;
}

function value(expr: string, x: number): number {
  return evaluate(parseExpression(expr, 'x'), 'x', x);
}

describe('the expression language', () => {
  it('accounts for all 162 recorded evaluations', () => {
    expect(VECTORS.eval).toHaveLength(162);
    const seenCorrections = new Set<string>();
    const seenAbsences = new Set<string>();

    for (const row of VECTORS.eval) {
      const x = real(row.x);
      const label = `${row.expr} at x=${row.x}`;

      const fix = corrected(row.expr, x);
      if (fix !== null) {
        seenCorrections.add(row.expr);
        if (Number.isNaN(fix.value)) expect(value(row.expr, x), label).toBeNaN();
        else expect(value(row.expr, x), `${label} — ${fix.why}`).toBe(fix.value);
        continue;
      }

      if (NOT_IN_THE_LANGUAGE.includes(row.expr)) {
        seenAbsences.add(row.expr);
        expect(() => value(row.expr, x), label).toThrow(PlotError);
        continue;
      }

      const want = real(row.result);
      if (isLibmRow(row.expr, x)) {
        // Same value, possibly not the same last bit.
        expect(Math.abs(value(row.expr, x) - want) / Math.abs(want), label).toBeLessThan(1e-15);
        continue;
      }
      if (Number.isNaN(want)) {
        // NaN and not its payload: V8's libm returns a quiet NaN spelt
        // 7ffc000000000000 where Rust's returns 7ff8000000000000, and no
        // program can tell the difference.
        expect(value(row.expr, x), label).toBeNaN();
        continue;
      }
      expect(bits(value(row.expr, x)), label).toBe(row.resultBits);
    }

    // Both tables are fully exercised by the corpus.
    expect(seenCorrections.size).toBe(new Set(CORRECTED_EVAL.map((row) => row.expr)).size);
    expect(seenAbsences.size).toBe(NOT_IN_THE_LANGUAGE.length);
  });

  it('rejects every one of the 38 malformed expressions', () => {
    expect(VECTORS.parseErrors).toHaveLength(38);
    for (const row of VECTORS.parseErrors) {
      // Two of the site's failures are not failures here, and both are in the
      // grammar on purpose: `floor(x)` is correction 1, and `x ++ 2` is
      // `x + (+2)` — unary plus is a prefix operator in SPEC §1.3's table.
      if (row.expr === 'floor(x)' || row.expr === 'x ++ 2') continue;
      expect(() => value(row.expr, 1), row.expr).toThrow(PlotError);
    }
  });

  it('says what is wrong, in the words SPEC §1.7 uses', () => {
    expect(() => value('sinc(x)', 1)).toThrow("unknown function 'sinc'");
    expect(() => value('sin(x', 1)).toThrow("expected ')'");
    expect(() => value('sqrt(1,2)', 1)).toThrow('sqrt takes 1 argument, not 2');
    expect(() => value('y', 1)).toThrow("unknown name 'y'");
  });

  it('binds unary minus looser than ^, and ^ to the right', () => {
    expect(value('2^3^2', 0)).toBe(512);
    expect(value('2^(3^2)', 0)).toBe(512);
    expect(value('(2^3)^2', 0)).toBe(64);
    expect(value('-x^2', 3)).toBe(-9);
    expect(value('(-x)^2', 3)).toBe(9);
    expect(value('-2^2', 0)).toBe(-4);
    expect(value('2^-1', 0)).toBe(0.5);
    expect(value('-x', 3)).toBe(-3);
    expect(value('--x', 3)).toBe(3);
  });

  it('knows pi and e, and nothing else without parentheses', () => {
    expect(value('pi', 0)).toBe(Math.PI);
    expect(value('e', 0)).toBe(Math.E);
    expect(value('e^2', 0)).toBe(7.3890560989306495);
    expect(() => value('sin', 0)).toThrow('sin is a function');
  });
});

// MARK: - §3b pow, the one place the four ports could silently disagree

describe('pow(±1, …) is 1, where JavaScript and Java say NaN', () => {
  // Measured across the ports: five inputs, and the four split 2-vs-2.
  //
  //     pow(1, NaN)  pow(1, +inf)  pow(1, -inf)  pow(-1, +inf)  pow(-1, -inf)
  //     Swift / Rust : 1.0        JS / Java : NaN
  //
  // C99 §F.9.4.4 and IEEE 754-2019 §9.2 both say pow(+1, y) is 1 for *any* y,
  // NaN included, and that pow(±1, ±inf) is 1; Swift's pow and Rust's powf —
  // which is what the site itself runs — follow that. ECMA-262's
  // Number::exponentiate returns NaN as soon as the exponent is NaN or the
  // base's magnitude is 1 and the exponent infinite, and Java agrees with it.
  // SPEC §1.3 makes everything here an IEEE-754 double, and one raised to
  // anything is one, so Swift and Rust are right and the JavaScript reference
  // is corrected to match — in `pow(a, b)` and in `^` alike.

  /** The five, spelled with the language's own non-finite values. */
  const SPECIAL: { name: string; call: string; operator: string }[] = [
    { name: 'pow(1, NaN)', call: 'pow(1, 0/0)', operator: '1^(0/0)' },
    { name: 'pow(1, +inf)', call: 'pow(1, 1/0)', operator: '1^(1/0)' },
    { name: 'pow(1, -inf)', call: 'pow(1, -(1/0))', operator: '1^(-(1/0))' },
    { name: 'pow(-1, +inf)', call: 'pow(-1, 1/0)', operator: '(-1)^(1/0)' },
    { name: 'pow(-1, -inf)', call: 'pow(-1, -(1/0))', operator: '(-1)^(-(1/0))' },
  ];

  it.each(SPECIAL)('$name is 1, as a call and as the ^ operator', (row) => {
    expect(value(row.call, 0), row.call).toBe(1);
    expect(value(row.operator, 0), row.operator).toBe(1);
  });

  it('is the platform that is wrong here, not the expectation', () => {
    // Pinned so that the day a JavaScript engine adopts the C99 rule, this
    // test is what says the override may go — and until then, what it is for.
    expect(Number.isNaN(Math.pow(1, Number.NaN))).toBe(true);
    expect(Number.isNaN(Math.pow(1, Number.POSITIVE_INFINITY))).toBe(true);
    expect(Number.isNaN(Math.pow(1, Number.NEGATIVE_INFINITY))).toBe(true);
    expect(Number.isNaN(Math.pow(-1, Number.POSITIVE_INFINITY))).toBe(true);
    expect(Number.isNaN(Math.pow(-1, Number.NEGATIVE_INFINITY))).toBe(true);
  });

  it('leaves every neighbouring case exactly as the platform has it', () => {
    // pow(x, ±0) is 1 for every x including NaN — already true everywhere.
    expect(value('pow(0/0, 0)', 0)).toBe(1);
    expect(value('(0/0)^0', 0)).toBe(1);
    // pow(x, NaN) is NaN for every x *but* 1 — including -1.
    expect(Number.isNaN(value('pow(-1, 0/0)', 0))).toBe(true);
    expect(Number.isNaN(value('(-1)^(0/0)', 0))).toBe(true);
    expect(Number.isNaN(value('pow(2, 0/0)', 0))).toBe(true);
    // And the ordinary infinite exponents keep their ordinary answers.
    expect(value('pow(2, 1/0)', 0)).toBe(Number.POSITIVE_INFINITY);
    expect(value('pow(2, -(1/0))', 0)).toBe(0);
    expect(value('pow(0.5, 1/0)', 0)).toBe(0);
    expect(value('pow(-1, 3)', 0)).toBe(-1);
    expect(value('1^2', 0)).toBe(1);
    expect(value('(-1)^2', 0)).toBe(1);
  });
});

// MARK: - §4 The four corrected behaviours, as figures

/** Everything a rendered figure can be asked about without an XML parser. */
function facts(svg: string): {
  lines: number;
  texts: number;
  polylines: number;
  first: string | null;
  last: string | null;
  xLabels: string[];
  yLabels: string[];
} {
  const runs = [...svg.matchAll(/<polyline points="([^"]*)"/g)].map((match) => match[1]);
  const lastRun = runs.length > 0 ? runs[runs.length - 1].split(' ') : null;
  return {
    lines: (svg.match(/<line /g) ?? []).length,
    texts: (svg.match(/<text /g) ?? []).length,
    polylines: runs.length,
    first: runs.length > 0 ? runs[0].split(' ')[0] : null,
    last: lastRun !== null ? lastRun[lastRun.length - 1] : null,
    xLabels: [...svg.matchAll(/text-anchor="middle">([^<]*)<\/text>/g)].map((m) => m[1]),
    yLabels: [...svg.matchAll(/dominant-baseline="middle">([^<]*)<\/text>/g)].map((m) => m[1]),
  };
}

function figure(source: string): ReturnType<typeof facts> {
  return facts(plotSVG(source));
}

describe('the four corrected behaviours (SPEC §1.3)', () => {
  it('1. floor, ceil and round draw a curve where the site draws nothing', () => {
    // `broken_floor_no_curve.svg` has 0 polylines. Here the staircase is one
    // run: floor(x) stays inside [-2, 2] for x in [-2, 3), and every step lands
    // inside the window, so nothing breaks it.
    const floor = figure('x: -10..10\ny: -2..2\nfloor(x)');
    expect(floor.polylines).toBe(1);
    expect(floor.first).toBe('248.00,360.00'); // x = -2, y = -2: the bottom left
    expect(floor.last).toBe('377.48,40.00'); // x = 2.98, y = 2: the top of the last step
    expect(figure('x: -10..10\ny: -2..2\nceil(x)').polylines).toBeGreaterThan(0);
    expect(figure('x: -10..10\ny: -2..2\nround(x)').polylines).toBeGreaterThan(0);
  });

  it('2. a comparison is a number, so (x>0)*sqrt(x) draws a half-domain curve', () => {
    // `boolean_no_curve.svg` has 0 polylines for `x>0`.
    const step = figure('x: -10..10\ny: -2..2\nx>0');
    expect(step.polylines).toBe(1);
    expect(step.first).toBe('40.00,200.00'); // 0 at the far left
    expect(step.last).toBe('560.00,120.00'); // 1 at the far right

    // The spec's own idiom. It draws exactly the half-domain it names: NaN
    // times zero is still NaN, so the left half stays empty and the curve
    // begins at the origin.
    const half = figure('x: -4..4\ny: -1..3\n(x>0)*sqrt(x)');
    expect(half.polylines).toBe(1);
    expect(half.first).toBe('300.00,280.00'); // x = 0, y = 0
    expect(half.last).toBe('560.00,120.00'); // x = 4, y = 2

    // And where the guard has a finite value on both sides it is a full-width
    // curve with a kink — a rectifier, drawn from edge to edge.
    const relu = figure('x: -4..4\ny: -1..3\n(x>0)*x');
    expect(relu.polylines).toBe(1);
    expect(relu.first).toBe('40.00,280.00');
    // …until it climbs out of the window at y = 3, which is where the run ends.
    expect(relu.last).toBe('495.00,40.00');
  });

  it('3. 2^3^2 is 512 in a figure, not 64', () => {
    // A constant series is a flat line, so its height *is* the value: with
    // y: 0..1024 the line at 512 lands exactly halfway.
    const chart = figure('x: -1..1\ny: 0..1024\n2^3^2');
    expect(chart.first).toBe('40.00,200.00');
    expect(chart.last).toBe('560.00,200.00');
  });

  it('4. 5/2 is 2.5, and the site draws it at 2', () => {
    // `int_division_trunc.svg` puts the line at y = 232, which is sy(2).
    const chart = figure('x: -1..1\ny: 0..5\n5/2');
    expect(chart.first).toBe('40.00,200.00'); // sy(2.5)
    expect(chart.last).toBe('560.00,200.00');
  });
});

describe('the two corrected axis behaviours (SPEC §1.4)', () => {
  it('labels a tick at −4 "-4", where the site truncates to "-3"', () => {
    // `tick_label_truncation.svg`, both axes [-5, -3]: the site's sixth label
    // reads "-3", out of order, in the middle of the axis.
    const chart = figure('x: -5..-3\ny: -5..-3\nx');
    expect(chart.xLabels[5]).toBe('-4');
    expect(chart.yLabels[5]).toBe('-4');
    expect(chart.xLabels).toEqual([
      '-5', '-4.80', '-4.60', '-4.40', '-4.20', '-4', '-3.80', '-3.60', '-3.40', '-3.20', '-3',
    ]);
  });

  it('labels the tick at the origin "0", where the site drifts to "-5.6e-17"', () => {
    // `tick_drift_zero_label.svg`: `gx += step` over [-1, 1] at 0.2 never
    // lands on zero. `first + i * step` does.
    const chart = figure('x: -1..1\ny: -1..1\nx');
    expect(chart.xLabels[5]).toBe('0');
    expect(chart.yLabels[5]).toBe('0');
    // And `tick_drift_extra_tick.svg`, where the drift is 1.4e-16 instead.
    expect(figure('x: -0.9..0.3\ny: -0.9..0.3\nx').xLabels[9]).toBe('0');
  });

  it('keeps the tick that lands exactly on the maximum', () => {
    // The other half of computing by index: `0.0001 + 8 * 0.0001` is
    // 9.000000000000001e-4, a hair over the range's own maximum, and dropping
    // the last tick of an axis because of one ULP is a visible defect. The
    // site drops it (`tiny_range.svg` has eight ticks per axis).
    const chart = figure('x: 0.0001..0.0009\ny: 0.0001..0.0009\nx');
    expect(chart.xLabels).toHaveLength(9);
    expect(chart.xLabels[8]).toBe('9.0e-4');
  });
});

// MARK: - §5 The 22 recorded figures

/**
 * The figures whose recorded shape is one of the six corrected behaviours.
 *
 * Each entry lists only what differs from the vector; everything unlisted is
 * still asserted against the site's own numbers.
 */
const CORRECTED_FIGURES: Readonly<
  Record<
    string,
    Partial<{
      polylines: number;
      first: string | null;
      last: string | null;
      lines: number;
      texts: number;
      xLabels: string[];
      yLabels: string[];
      why: string;
    }>
  >
> = {
  // floor(x) draws (correction 1).
  broken_floor_no_curve: {
    polylines: 1,
    first: '248.00,360.00',
    last: '377.48,40.00',
    why: 'floor is bound',
  },
  // x>0 draws (correction 2).
  boolean_no_curve: {
    polylines: 1,
    first: '40.00,200.00',
    last: '560.00,120.00',
    why: 'a comparison is a number',
  },
  // 5/2 is 2.5, and the origin's label is "0" and not "-5.6e-17".
  int_division_trunc: {
    first: '40.00,200.00',
    last: '560.00,200.00',
    xLabels: ['-1', '-0.80', '-0.60', '-0.40', '-0.20', '0', '0.20', '0.40', '0.60', '0.80', '1'],
    why: 'no integer division; no tick drift',
  },
  constant_three: {
    xLabels: ['-1', '-0.80', '-0.60', '-0.40', '-0.20', '0', '0.20', '0.40', '0.60', '0.80', '1'],
    why: 'no tick drift',
  },
  tick_drift_zero_label: {
    xLabels: ['-1', '-0.80', '-0.60', '-0.40', '-0.20', '0', '0.20', '0.40', '0.60', '0.80', '1'],
    yLabels: ['-1', '-0.80', '-0.60', '-0.40', '-0.20', '0', '0.20', '0.40', '0.60', '0.80', '1'],
    why: 'no tick drift',
  },
  tick_drift_extra_tick: {
    xLabels: [
      '-0.90', '-0.80', '-0.70', '-0.60', '-0.50', '-0.40', '-0.30', '-0.20', '-0.10', '0',
      '0.10', '0.20', '0.30',
    ],
    yLabels: [
      '-0.90', '-0.80', '-0.70', '-0.60', '-0.50', '-0.40', '-0.30', '-0.20', '-0.10', '0',
      '0.10', '0.20', '0.30',
    ],
    why: 'no tick drift',
  },
  // The truncated label, and the tick at the maximum the site's accumulation
  // overshot: eleven ticks per axis rather than ten.
  tick_label_truncation: {
    lines: 22,
    texts: 22,
    xLabels: [
      '-5', '-4.80', '-4.60', '-4.40', '-4.20', '-4', '-3.80', '-3.60', '-3.40', '-3.20', '-3',
    ],
    yLabels: [
      '-5', '-4.80', '-4.60', '-4.40', '-4.20', '-4', '-3.80', '-3.60', '-3.40', '-3.20', '-3',
    ],
    why: 'labels are rounded, and the last tick is kept',
  },
  no_zero_on_either_axis: {
    lines: 20,
    texts: 20,
    xLabels: ['1', '1.20', '1.40', '1.60', '1.80', '2', '2.20', '2.40', '2.60', '2.80', '3'],
    why: 'labels are rounded, and the last tick is kept',
  },
  tiny_range: {
    lines: 18,
    texts: 18,
    xLabels: [
      '1.0e-4', '2.0e-4', '3.0e-4', '4.0e-4', '5.0e-4', '6.0e-4', '7.0e-4', '8.0e-4', '9.0e-4',
    ],
    yLabels: [
      '1.0e-4', '2.0e-4', '3.0e-4', '4.0e-4', '5.0e-4', '6.0e-4', '7.0e-4', '8.0e-4', '9.0e-4',
    ],
    why: 'the tick on the maximum is kept',
  },
};

describe('the 22 recorded figures', () => {
  it('draws thirteen of them exactly as the site does', () => {
    expect(VECTORS.svg).toHaveLength(22);
    let same = 0;
    for (const row of VECTORS.svg) {
      if (CORRECTED_FIGURES[row.name] === undefined) same++;
    }
    expect(same).toBe(13);
  });

  for (const row of VECTORS.svg) {
    it(`${row.name}: ${row.expr}`, () => {
      const source = `x: ${row.xMin}..${row.xMax}\ny: ${row.yMin}..${row.yMax}\n${row.expr}`;
      const got = facts(plotSVG(source));
      const fix = CORRECTED_FIGURES[row.name] ?? {};

      // The spacing is `nice_step`, ported verbatim: never corrected.
      expect(bits(niceStep(row.xMax - row.xMin))).toBe(bits(row.xStep));
      expect(bits(niceStep(row.yMax - row.yMin))).toBe(bits(row.yStep));

      expect(got.lines, 'grid + axis lines').toBe(fix.lines ?? row.lineCount);
      expect(got.texts, 'tick labels').toBe(fix.texts ?? row.textCount);
      expect(got.polylines, 'unbroken runs').toBe(fix.polylines ?? row.polylineCount);
      expect(got.first, 'first plotted point').toBe(
        fix.first !== undefined ? fix.first : row.firstPoint,
      );
      expect(got.last, 'last plotted point').toBe(fix.last !== undefined ? fix.last : row.lastPoint);
      expect(got.xLabels, 'x tick labels').toEqual(fix.xLabels ?? row.xTickLabels);
      expect(got.yLabels, 'y tick labels').toEqual(fix.yLabels ?? row.yTickLabels);
    });
  }

  it('breaks a curve where it leaves the window, and nowhere else', () => {
    // tan(x) over [-10, 10] is seven branches; 1/x over [-5, 5] is two; a
    // single plottable sample is still a polyline of one point.
    expect(figure('x: -10..10\ny: -2..2\ntan(x)').polylines).toBe(7);
    expect(figure('x: -5..5\ny: -5..5\n1/x').polylines).toBe(2);
    expect(figure('x: -10..10\ny: -0.005..0.005\nx').first).toBe('300.00,200.00');
  });

  it('samples with the formula the site uses, not the cheaper one', () => {
    // `xMin + (i / samples) * span`, never `xMin + i * dx`: the two differ in
    // the last bits for 221 of the 1001 default samples, and the difference
    // reaches the output.
    const chart = figure('x: -6.3..0.7999999999999998\ny: -3.3..3.1\nx');
    expect(chart.first).toBe('259.96,359.83');
    expect(chart.last).toBe('560.00,155.00');
  });
});

// MARK: - §6 The fence

describe('the fence', () => {
  it('reads directives in any order, and ignores blanks and comments', () => {
    const spec = parsePlot(
      ['# a comment', '', 'sin(x)', 'title: A title', 'x: -1..1', 'y: -2..2', ''].join('\n'),
    );
    expect(spec.title).toBe('A title');
    expect(spec.xMin).toBe(-1);
    expect(spec.xMax).toBe(1);
    expect(spec.yMin).toBe(-2);
    expect(spec.series).toHaveLength(1);
  });

  it('treats an unknown key: line as a labelled series, not as an error', () => {
    // `f: x` still plots. This is why the directive scan checks the key
    // against the known list before it claims the line, and why the series
    // parser then reads the key as a label.
    const spec = parsePlot('f: x');
    expect(spec.series).toHaveLength(1);
    expect(spec.series[0].label).toBe('f');
    expect(spec.series[0].source).toBe('x');
    expect(plotSVG('f: sin(x)')).toContain('<polyline');
  });

  it('defaults to -10..10, auto, 600 × 400, 1000 samples', () => {
    const spec = parsePlot('sin(x)');
    expect([spec.xMin, spec.xMax]).toEqual([-10, 10]);
    expect(spec.yMin).toBeNull();
    expect([spec.width, spec.height, spec.samples]).toEqual([600, 400, 1000]);
    expect(spec.legend).toBe('auto');
    expect(spec.grid).toBe(true);
    expect(spec.axes).toBe(true);
  });

  it('clamps width, height and samples', () => {
    expect(parsePlot('width: 10\nheight: 10\nsamples: 1\nx').width).toBe(160);
    expect(parsePlot('width: 10\nheight: 10\nsamples: 1\nx').height).toBe(120);
    expect(parsePlot('width: 10\nheight: 10\nsamples: 1\nx').samples).toBe(50);
    expect(parsePlot('width: 9000\nheight: 9000\nsamples: 90000\nx').width).toBe(2000);
    expect(parsePlot('width: 9000\nheight: 9000\nsamples: 90000\nx').height).toBe(2000);
    expect(parsePlot('width: 9000\nheight: 9000\nsamples: 90000\nx').samples).toBe(5000);
  });

  it('takes a constant expression at either end of a range', () => {
    const spec = parsePlot('x: -pi..2*pi\nsin(x)');
    expect(spec.xMin).toBe(-Math.PI);
    expect(spec.xMax).toBe(2 * Math.PI);
  });

  it('rejects a range that does not increase', () => {
    expect(() => parsePlot('x: 1..1\nx')).toThrow('x range must be increasing');
    expect(() => parsePlot('y: 5..-5\nx')).toThrow('y range must be increasing');
    expect(() => parsePlot('x: nonsense\nx')).toThrow(PlotError);
  });

  it('splits a label off the first top-level bare =', () => {
    expect(parsePlot('envelope = exp(-abs(x)/5)').series[0].label).toBe('envelope');
    expect(parsePlot('envelope = exp(-abs(x)/5)').series[0].source).toBe('exp(-abs(x)/5)');
    // The FIRST one, so what follows still has to be an expression: there is
    // no assignment in the language for a second `=` to be part of.
    expect(() => parsePlot('a = b = x')).toThrow(PlotError);
    // …and never off a comparison operator.
    for (const source of ['x == 1', 'x <= 1', 'x >= 1', 'x != 1']) {
      expect(parsePlot(source).series[0].label, source).toBeNull();
    }
  });

  it('reads a points series and a parametric series', () => {
    const points = parsePlot('measured = points: 0,0 1,2 2,1').series[0];
    expect(points.kind).toBe('points');
    expect(points.label).toBe('measured');
    expect(points.points).toEqual([
      { x: 0, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
    ]);

    const parametric = parsePlot('circle = (cos(t), sin(t)) for t in 0..2*pi').series[0];
    expect(parametric.kind).toBe('parametric');
    expect(parametric.parameter).toBe('t');
    expect(parametric.tMin).toBe(0);
    expect(parametric.tMax).toBe(2 * Math.PI);
    // The parametric variable is the only free name inside it: `x` is not.
    expect(() => parsePlot('(x, sin(t)) for t in 0..1')).toThrow("unknown name 'x'");
  });

  it('does not mistake a parenthesised expression for a parametric one', () => {
    expect(parsePlot('(x+1)*2').series[0].kind).toBe('function');
    // A pair with no `for` is not a parametric series, so it is read as an
    // expression — and a tuple is not one of those.
    expect(() => parsePlot('(x, x)')).toThrow(PlotError);
  });

  it('fits y: auto to the finite samples, with 5 % of padding', () => {
    // sin over a whole period reaches ±1 (to the last sample), so the window
    // is 1.05 either way.
    const svg = plotSVG('x: -10..10\nsin(x)');
    expect(svg).toContain('>1</text>'); // a tick at 1 is inside the window
    // A series with nothing finite in it falls back to -1..1.
    expect(plotSVG('x: -10..10\nsqrt(-1)+x*0')).toContain('>1</text>');
    // A flat series has no span to take 5 % of: it is padded by 5 % of itself.
    const flat = parsePlot('x: -1..1\n3');
    expect(flat.series).toHaveLength(1);
    expect(plotSVG('x: -1..1\n3')).toContain('<polyline');
  });

  it('shows the legend when there are two series, or one that is labelled', () => {
    expect(plotSVG('x: -1..1\nsin(x)')).not.toContain('font-size="11" font-family="sans-serif"');
    expect(plotSVG('x: -1..1\nsin(x)\ncos(x)')).toContain('font-size="11" font-family="sans-serif"');
    expect(plotSVG('x: -1..1\nwave = sin(x)')).toContain('>wave</text>');
    expect(plotSVG('x: -1..1\nlegend: off\nsin(x)\ncos(x)')).not.toContain(
      'font-size="11" font-family="sans-serif"',
    );
    // An unlabelled series' legend text is its own source.
    expect(plotSVG('x: -1..1\nlegend: on\nsin(x)')).toContain('>sin(x)</text>');
  });

  it('turns the grid and the axes off', () => {
    const bare = plotSVG('x: -1..1\ngrid: off\naxes: off\nx');
    expect(bare).not.toContain('<line');
    expect(bare).not.toContain('<text x=');
    expect(bare).not.toContain('<rect');
    expect(bare).toContain('<polyline');
    expect(() => parsePlot('grid: sometimes\nx')).toThrow("grid must be 'on' or 'off'");
  });

  it('gives each series the next colour, purple first', () => {
    const svg = plotSVG('x: -1..1\nx\nx+0.1\nx+0.2');
    expect(svg).toContain('stroke="#673AB7"');
    expect(svg).toContain('stroke="#E5390F"');
    expect(svg).toContain('stroke="#0F9D58"');
  });
});

// MARK: - §7 The container, and what must never be in it

describe('the emitted markup', () => {
  const svg = plotSVG('x: -10..10\ntitle: T\nsin(x)');

  it('is a div.plot around one svg with a viewBox', () => {
    const block = renderPlot('x: -10..10\nsin(x)');
    expect(block.startsWith('<div class="plot"><svg ')).toBe(true);
    expect(block.endsWith('</svg></div>')).toBe(true);
    // Without a viewBox, `max-width: 100%; height: auto` shrinks the box and
    // clips the drawing instead of scaling it.
    expect(block).toContain('viewBox="0 0 600 400"');
    expect(block).toContain('width="600" height="400" role="img"');
  });

  it('carries no id at all', () => {
    // SPEC §1.5: a duplicated id is how one figure ends up wearing another's
    // clip path once a document holds two plots and morphdom patches the
    // preview. An `<svg role="img">` is named by its own `<title>`, with no
    // `aria-labelledby` to point at, so there is nothing to number.
    const two = renderPlot('sin(x)') + renderPlot('cos(x)');
    expect(two).not.toContain(' id=');
    expect(two).not.toContain('aria-labelledby');
    expect(svg).toContain('<title>T</title>');
    expect(plotSVG('sin(x)')).toContain('<title>Plot of sin(x)</title>');
  });

  it('paints with currentColor and bakes only the series colours', () => {
    // `renderBlock` is theme-blind in all four repos, so one SVG has to be
    // right in a light preview, a dark preview, print, an exported page and a
    // saved file. A baked grey is a light-mode assumption.
    expect(svg).toContain('stroke="currentColor"');
    expect(svg).toContain('fill="currentColor"');
    for (const grey of ['#e0e0e0', '#999', '#666', '#ccc']) expect(svg).not.toContain(grey);
    expect(svg).not.toContain('background:white');
    expect(svg).toContain('stroke="#673AB7"');
  });

  it('embeds no style, script, foreignObject or font', () => {
    // An SVG `<style>` inside an HTML document is document-scoped and leaks.
    for (const forbidden of ['<style', '<script', '<foreignObject', '@font-face', '<image']) {
      expect(svg, forbidden).not.toContain(forbidden);
    }
  });

  it('XML-escapes every author string, with the five XML entities and no other', () => {
    // The EPUB body is XHTML, which is XML: one raw `&` makes the whole
    // content document unparseable and the book unopenable. And a named
    // entity like `&nbsp;` is undefined in XML, so escaping may only ever
    // produce the five.
    const hostile = plotSVG(
      ['title: A & B <c> "d"', 'xlabel: <x>', 'ylabel: &y;', 'p & q = x'].join('\n'),
    );
    expect(hostile).toContain('<title>A &amp; B &lt;c&gt; &quot;d&quot;</title>');
    expect(hostile).toContain('>&lt;x&gt;</text>');
    expect(hostile).toContain('>&amp;y;</text>');
    expect(hostile).toContain('>p &amp; q</text>');
    expect(hostile).not.toContain('&nbsp;');
    for (const entity of [...hostile.matchAll(/&[a-z]+;/g)].map((m) => m[0])) {
      expect(['&amp;', '&lt;', '&gt;', '&quot;', '&apos;']).toContain(entity);
    }
  });

  it('emits the container even for an empty block and a broken one', () => {
    // If it is ever omitted the SVG-export ordinals desynchronise and every
    // later diagram exports the wrong figure.
    expect(renderPlot('')).toBe('<div class="plot"></div>');
    expect(renderPlot('# only a comment')).toBe('<div class="plot"></div>');
    const broken = renderPlot('sinc(x)');
    expect(broken.startsWith('<div class="plot"><pre>')).toBe(true);
    expect(broken).toContain("plot: unknown function 'sinc'");
    expect(broken).toContain('sinc(x)'); // the source always stays visible
    expect(renderPlot('x: 1..1\nx')).toContain('plot: x range must be increasing');
  });

  it('escapes the source it falls back to', () => {
    expect(renderPlot('<b>&</b>')).toContain('&lt;b&gt;&amp;&lt;/b&gt;');
  });

  it('never returns anything but a container, whatever it is handed', () => {
    // The renderer runs inside the Markdown renderer, which has no other
    // failure mode: whatever a fence contains, the answer is a `div.plot` with
    // either a drawing or the source in it, and every coordinate in that
    // drawing is a real number. A stack overflow on 200 nested parentheses is
    // caught here too — it is a RangeError rather than a PlotError, and it
    // still comes back as the author's own text.
    const hostile = [
      '', '   ', '#', 'x: 0..0\nx', 'y: 1..0\nx', 'width: -5\nheight: abc\nx',
      'points:', 'points: 1', 'label =', '= x', '(cos(t), sin(t)) for t in 0..0',
      '(cos(t), sin(t)) for u in 0..1', 'x: 1e308..-1e308\nx', 'x: -1e308..1e308\nx',
      'x: 0.0000001..0.0000002\nx', 'axes: off\ngrid: off\nx', 'ln(x)', 'x^x',
      'sqrt(-x)', '0/0', 'x*0/0', '('.repeat(200) + 'x', 'title: ' + 'A'.repeat(500) + '\nx',
      'y: -1..1\n' + 'sin(x)\n'.repeat(12),
    ];
    for (const source of hostile) {
      const html = renderPlot(source);
      expect(html.startsWith('<div class="plot">'), source).toBe(true);
      expect(html.endsWith('</div>'), source).toBe(true);
      for (const attribute of html.matchAll(/ (?:x|y|x1|y1|x2|y2|width|height|cx|cy)="([^"]*)"/g)) {
        expect(Number.isFinite(Number(attribute[1])), `${source} → ${attribute[1]}`).toBe(true);
      }
      for (const run of html.matchAll(/points="([^"]*)"/g)) {
        for (const pair of run[1].split(' ')) {
          const [x, y] = pair.split(',');
          expect(Number.isFinite(Number(x)) && Number.isFinite(Number(y)), pair).toBe(true);
        }
      }
    }
  });

  it('survives a figure squeezed to the smallest canvas', () => {
    // Title, both axis labels and a legend on a 160 × 120 canvas would compute
    // a negative plot area without `fitMargins`.
    const tiny = plotSVG(
      ['width: 160', 'height: 120', 'title: T', 'xlabel: x', 'ylabel: y', 'legend: on', 'a = x'].join('\n'),
    );
    expect(tiny).toContain('viewBox="0 0 160 120"');
    expect(tiny).not.toContain('NaN');
    // The plot area is still a real rectangle, inside the canvas.
    const rect = /<rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)"/.exec(tiny);
    expect(rect).not.toBeNull();
    const [x, y, w, h] = (rect as RegExpExecArray).slice(1).map(Number);
    expect(w).toBeGreaterThanOrEqual(40);
    expect(h).toBeGreaterThanOrEqual(40);
    expect(x + w).toBeLessThanOrEqual(160);
    expect(y + h).toBeLessThanOrEqual(120);
  });
});

// MARK: - §8 The renderer, the settings and every export path

const FENCE = ['```plot', 'x: -10..10', 'sin(x)', '```'].join('\n');

describe('integration', () => {
  it('dispatches the fence to a plot container', () => {
    const { html, needs } = renderBody(FENCE, { title: 't', dark: false });
    expect(html.startsWith('<div class="plot"><svg')).toBe(true);
    // The class is exactly `plot`, which keeps all five engine probes false: a
    // plot-only document loads no engine at all, and there is no `needs` flag
    // to add.
    expect(needs).toEqual({
      math: false,
      mermaid: false,
      plantuml: false,
      graphviz: false,
      highlight: false,
    });
  });

  it('leaves the source visible when md.diagrams.plot is off', () => {
    const html = renderBody(FENCE, { title: 't', dark: false, plot: false }).html;
    expect(html).toBe('<div class="plot"><pre>x: -10..10\nsin(x)</pre></div>');
  });

  it('is styled by both stylesheets — the exported one and the preview’s', () => {
    // Two sheets, because VS Code's built-in preview is styled by
    // `media/preview/md-preview.css` and every export by `css-text.ts`. The
    // rules are *joined*, never added: `html.test.ts` pins each variant at
    // exactly 101 lines.
    const exported = renderDocument(FENCE, { title: 't', dark: false });
    expect(exported).toContain('.mermaid, .plantuml, .graphviz, .plot, .md-mathd {');
    expect(exported).toContain('.graphviz svg, .plot svg { max-width: 100%; height: auto; }');
    const preview = fs.readFileSync(
      path.join(__dirname, '..', 'media', 'preview', 'md-preview.css'),
      'utf8',
    );
    expect(preview).toContain('body .markdown-body .plot,');
    expect(preview).toContain('body .markdown-body .plot svg {');
  });

  it('offers the figure to the SVG export, and finds it in the DOM', () => {
    const document = [FENCE, '', '```dot', 'digraph {}', '```'].join('\n');
    const found = diagrams(document);
    expect(found.map((d) => d.kind)).toEqual(['plot', 'graphviz']);
    expect(typeName(found[0])).toBe('Plot');
    expect(menuTitle(found[0])).toBe('Plot: x: -10..10');
    // The walk and the DOM query must agree about what a diagram is, or every
    // later figure exports as the wrong one.
    expect(DIAGRAM_SELECTOR).toContain('div.plot');
    // A quoted plot keeps its place, because the renderer recurses into quotes.
    expect(diagrams(['> ```plot', '> sin(x)', '> ```'].join('\n')).map((d) => d.kind)).toEqual([
      'plot',
    ]);
  });

  it('saves as a standalone .svg without a fix-up', () => {
    // The root already carries `xmlns`, `width` and `height`, so the only
    // thing the writer adds is the XML prolog.
    const file = standaloneDocument(plotSVG('sin(x)'));
    expect(file.startsWith('<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns=')).toBe(true);
    expect(file).toContain('width="600" height="400"');
  });

  it('keeps the source in the LaTeX export, under a comment', () => {
    const tex = latexDocument(FENCE);
    expect(tex).toContain('% plot diagram source');
    expect(tex).toContain('\\begin{verbatim}');
    expect(tex).toContain('sin(x)');
  });

  it('passes the EPUB’s XHTML fixer untouched, and asks for properties="svg"', () => {
    // The fixers have never seen an SVG before: `xhtml` self-closes void
    // elements with an *unanchored* alternation, so `<line>` and `<polyline>`
    // are exactly the shapes to check before trusting it.
    const body = renderBody(FENCE, { title: 't', dark: false }).html;
    expect(body).toContain('<line ');
    expect(body).toContain('<polyline ');
    expect(xhtml(body)).toBe(body);

    // EPUB 3 requires the reserved property on any content document holding an
    // `<svg>`; without it EPUBCheck reports OPF-014 and the book is invalid.
    expect(
      contentOPF({
        title: 't',
        identifier: 'i',
        modified: 'm',
        units: [{ id: 'content', href: 'content.xhtml', svg: true }],
        images: [],
      }),
    ).toContain('<item id="content" href="content.xhtml" media-type="application/xhtml+xml" properties="svg"/>');
    // …and a document without one is still emitted bare.
    expect(
      contentOPF({
        title: 't',
        identifier: 'i',
        modified: 'm',
        units: [{ id: 'content', href: 'content.xhtml' }],
        images: [],
      }),
    ).toContain('<item id="content" href="content.xhtml" media-type="application/xhtml+xml"/>');
  });
});

// MARK: - §9 The figure itself, byte for byte

describe('golden figure', () => {
  // The whole SVG of one document, pinned. Not a specification and not
  // documentation: a tripwire, so that a change to a coordinate, an opacity or
  // an attribute order shows up as a diff to read rather than as nothing at
  // all. Regenerate with `npx vitest run -u` and read every hunk.
  //
  // It is also the file the three other ports are diffed against: same fence,
  // same bytes, in Swift and in Kotlin.
  it('draws the spec’s own example as recorded', async () => {
    const source = [
      'x: -10..10',
      'y: -2..2',
      'title: Damped oscillation',
      'xlabel: x',
      'ylabel: amplitude',
      'envelope = exp(-abs(x)/5)',
      'sin(x) * exp(-abs(x)/5)',
    ].join('\n');
    await expect(renderPlot(source) + '\n').toMatchFileSnapshot(
      path.join(GOLDEN, 'plot-damped-oscillation.svg'),
    );
  });
});

describe('resource limits and degenerate magnitudes', () => {
  // Each of these was found by an adversarial pass against the first cut of
  // this file, and each is a way the reference could have taught the same
  // defect to the Swift and Kotlin ports. A stack overflow is an exception
  // here and a crash there, so the guards matter more downstream than they do
  // in this repo.

  it('draws a series whose values overflow the padded range', () => {
    // `high - low` overflows for a series straddling ~1e308, which made every
    // sy() NaN and emitted points="40.00,NaN …" — a curve that vanished with
    // nothing to say why.
    const out = renderPlot('x: -10..10\nx*1e307');
    expect(out).not.toContain('NaN');
    expect(out).toContain('<polyline');
  });

  it('leaves a huge but narrow range exactly as asked', () => {
    // The guard must fire on an overflowing *width*, not on a large bound:
    // [1.69e308, 1.71e308] is only 2e306 wide and is perfectly drawable.
    const out = renderPlot('x: -1..1\ny: 1.69e308..1.71e308\n1.7e308');
    expect(out).not.toContain('NaN');
    expect(out).toContain('<polyline');
  });

  it('reports deep nesting as a plot: line, not a stack overflow', () => {
    const source = 'x: -1..1\n' + '('.repeat(5000) + 'x' + ')'.repeat(5000);
    expect(renderPlot(source)).toContain('plot: expression nested too deeply');
  });

  it('reports a long flat chain too, which the depth guard cannot see', () => {
    // `x+x+x+…` parses at constant depth through the left-associative loop and
    // then overflows the stack in the evaluator, so depth alone is not enough.
    const source = 'x: -1..1\n' + 'x' + '+x'.repeat(20000);
    expect(renderPlot(source)).toContain('plot: expression too large');
  });

  it('caps the series count, the one input with no clamp', () => {
    const source = 'x: -1..1\n' + Array.from({ length: 1000 }, (_, i) => `x*${i + 1}`).join('\n');
    expect(renderPlot(source)).toContain('plot: too many series');
  });

  it('draws the axes a directives-only block describes', () => {
    // Not an empty block: the author wrote three lines. Returning an empty
    // container would swallow them, and the family rule is never a hole.
    const out = renderPlot('x: -10..10\ntitle: My chart\nylabel: y');
    expect(out).toContain('<svg');
    expect(out).toContain('My chart');
  });

  it('still draws nothing for a genuinely empty block', () => {
    expect(renderPlot('')).toBe('<div class="plot"></div>');
  });
});

// MARK: - §10 The render cache

describe('the render cache', () => {
  // WHY IT EXISTS. The live preview rebuilds the whole HTML document on every
  // text change — the 0.35 s debounce delays the webview reload, not the
  // render — and a plot is the first rich fence whose real cost is paid at
  // that layer, synchronously, rather than in the page by an engine. Measured
  // in a release build on a Mac: 4.87 ms for one default plot, 9.52 ms for the
  // golden fence, 36 ms for an eight-series plot, 187 ms for a document with
  // four of those and 289 ms for ten `samples: 5000` plots. The per-fence
  // clamps bound a fence, not a document, and a phone is slower.
  //
  // `renderPlot` is a pure function of its source string, so memoising it on
  // exactly that string is sound by construction, and while prose is being
  // typed around them every plot in the document is a hit. Nothing in the
  // preview coordinator or the debounce is touched.

  const SOURCE = ['x: -10..10', 'y: -2..2', 'title: Damped', 'sin(x) * exp(-abs(x)/5)'].join('\n');

  it('serves a repeat render from the cache', () => {
    resetPlotCache();
    const first = renderPlot(SOURCE);
    expect(plotCacheStats()).toMatchObject({ hits: 0, misses: 1, size: 1 });

    const second = renderPlot(SOURCE);
    expect(plotCacheStats()).toMatchObject({ hits: 1, misses: 1, size: 1 });
    expect(second).toBe(first);

    // …and what the cache hands back is what a cold render produces, so the
    // memo can never be the reason two identical fences differ.
    resetPlotCache();
    expect(renderPlot(SOURCE)).toBe(first);
    expect(plotCacheStats()).toMatchObject({ hits: 0, misses: 1, size: 1 });
  });

  it('caches a failure too — the state a fence spends most of its life in', () => {
    resetPlotCache();
    const broken = 'x: -1..1\nsinc(x)';
    const out = renderPlot(broken);
    expect(out).toContain("plot: unknown function 'sinc'");
    expect(renderPlot(broken)).toBe(out);
    expect(plotCacheStats()).toMatchObject({ hits: 1, misses: 1, size: 1 });
  });

  it('holds 32 and evicts the least recently used', () => {
    resetPlotCache();
    expect(plotCacheStats().limit).toBe(32);

    const sources = Array.from({ length: 32 }, (_, i) => `x: -1..1\nx*${i + 1}`);
    for (const source of sources) {
      renderPlot(source);
      expect(plotCacheStats().size).toBeLessThanOrEqual(32);
    }
    expect(plotCacheStats()).toMatchObject({ hits: 0, misses: 32, size: 32 });

    // Touch the oldest entry so it becomes the newest. Eviction has to be by
    // *use*: otherwise the plot the author keeps re-rendering is the one thrown
    // away every 32 keystrokes.
    renderPlot(sources[0]);
    expect(plotCacheStats().hits).toBe(1);

    // The 33rd distinct fence evicts exactly one entry — and it is sources[1],
    // now the oldest by use, not sources[0], the oldest by insertion.
    renderPlot('x: -1..1\nx*33');
    expect(plotCacheStats().size).toBe(32);

    const hitsBefore = plotCacheStats().hits;
    renderPlot(sources[0]);
    expect(plotCacheStats().hits, 'sources[0] was touched and must have survived').toBe(
      hitsBefore + 1,
    );

    const missesBefore = plotCacheStats().misses;
    renderPlot(sources[1]);
    expect(plotCacheStats().misses, 'sources[1] was the least recently used and must be gone').toBe(
      missesBefore + 1,
    );
    expect(plotCacheStats().size).toBe(32);
  });

  it('never conflates two fences that differ by a character', () => {
    resetPlotCache();
    const sine = renderPlot('x: -1..1\nsin(x)');
    const cosine = renderPlot('x: -1..1\ncos(x)');
    expect(cosine).not.toBe(sine);
    expect(plotCacheStats()).toMatchObject({ hits: 0, misses: 2, size: 2 });
  });
});

// MARK: - Follow-up, deliberately not done here
//
// The shipped Examples document has no `plot` section yet. `test/fixtures/`
// mirrors `md/mdTests/TestData/` and the apps' Examples bundle across four
// repositories (byte for byte, but for `test.md`'s per-platform lines — see
// golden.test.ts), and each roster is pinned twice per repo, so a
// fixture added here alone would break the mirror rather than extend it. The
// example belongs in the port phase, added to all four at once.
